run-dev:
	python app/animals_dnk/manage.py runserver

run-prod:
	python manage.py runserver 0.0.0.0:8000 --noreload

makemigrates:
	python manage.py makemigrations

migrate:
	python manage.py migrate

makemigrations: makemigrates migrate