# Generated by Django 5.1.4 on 2024-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneticTests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_name", models.CharField(max_length=150)),
                ("species", models.CharField(max_length=60)),
                ("test_date", models.DateField(null=True)),
                ("milk_yield", models.FloatField(null=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[("good", "good"), ("poor", "poor")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
